---
title: "Analysis on the results of mate choice experiment"
author: "Keisuke Atsumi"
date: '`r format(Sys.time(), "%y/%m/%d %H:%M")`'
output: html_document
---


#### Abbreviations
TH: *Tribolodon hakonensis*
TS: *Tribolodon sachalinensis* 


```{r setup, eval=TRUE, include=FALSE}
rm(list=ls())  # reset workspace
options(scipen=100)  # do not show numbers using exponential

# install & load packages
library(tidyverse)  # dataset modification
library(knitr)
library(openxlsx)  # read Excel file
library(gridExtra)
library(MuMIn) # variable selection
library(lme4) # GLMM
library(lubridate)
```


```{r data wrangling, echo=FALSE}
######## Load data & calculate effect size ########
res <- read.xlsx("dace.matechoice.data.xlsx", sheet = 1)  %>%
  mutate_at(vars(contains("prop")), funs(as.numeric(.)))    %>%
  mutate(time.ratio.ln = log(prop.cons / prop.hetero))      %>%  # calculate effect size              
  mutate_at(vars(FL), funs(as.numeric(.))) %>%              
  mutate_at(vars(species, heterospecifics, type, contains("ID")), funs(as.factor(.)))

TS <- filter(res, species == "TS")
TH <- filter(res, species == "TH")

print(paste("earliest catch date", as.Date(min(res$catch.date, na.rm = T), origin = "1899-12-30")), sep = "\t")
print(paste("latest catch date", as.Date(max(res$catch.date, na.rm = T), origin = "1899-12-30")), sep = "\t")
print(paste("earliest exp date", as.Date(min(res$date, na.rm = T), origin = "1899-12-30")), sep = "\t")
print(paste("latest exp date", as.Date(max(res$date, na.rm = T), origin = "1899-12-30")), sep = "\t")
```


## Check distribution

```{r distribution, warning = FALSE}

############################
# time.ratio.ln 
############################

####### Probablity density plot #######
prob_dens.ratio.ln <- . %>% {
  ggplot(., aes(time.ratio.ln)) + geom_density(colour = "#9BD3EE", fill = "#D0F3FF70")
}
prob_dens.ratio.ln(TH) + ggtitle("Preference strength | TH") -> p1
prob_dens.ratio.ln(TS) + ggtitle("Preference strength | TS") -> p2
grid.arrange(p1, p2, ncol = 2)

####### Shapiro-Wilk test #######
# TH
shapiro.test(TH$time.ratio.ln)
# TS
shapiro.test(TS$time.ratio.ln)

```


## t-test on preference strength

```{r test parametric}

##### TH #####
t.test(x = TH$time.ratio.ln, alternative = "greater")
##### TS #####
t.test(x = TS$time.ratio.ln, alternative = "greater")
```

## Load violin-plot function

```{r flat-violin function, include=FALSE}
"%||%" <- function(a, b) {
  if (!is.null(a)) a else b
}
geom_flat_violin <- function(mapping = NULL, data = NULL, stat = "ydensity",
                        position = "dodge", trim = TRUE, scale = "area",
                        show.legend = NA, inherit.aes = TRUE, ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomFlatViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      ...
    )
  )
}
#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomFlatViolin <-
  ggproto("GeomFlatViolin", Geom,
          setup_data = function(data, params) {
            data$width <- data$width %||%
              params$width %||% (resolution(data$x, FALSE) * 0.9)
            # ymin, ymax, xmin, and xmax define the bounding rectangle for each group
            data %>%
              group_by(group) %>%
              mutate(ymin = min(y),
                     ymax = max(y),
                     xmin = x,
                     xmax = x + width / 2)
          },
          draw_group = function(data, panel_scales, coord) {
            # Find the points for the line to go all the way around
            data <- transform(data, xminv = x,
                              xmaxv = x + violinwidth * (xmax - x))
            # Make sure it's sorted properly to draw the outline
            newdata <- rbind(plyr::arrange(transform(data, x = xminv), y),
                             plyr::arrange(transform(data, x = xmaxv), -y))
            # Close the polygon: set first and last point the same
            # Needed for coord_polar and such
            newdata <- rbind(newdata, newdata[1,])
            ggplot2:::ggname("geom_flat_violin", GeomPolygon$draw_panel(newdata, panel_scales, coord))
          },
          draw_key = draw_key_polygon,
          default_aes = aes(weight = 1, colour = "grey20", fill = "white", size = 0.5,
                            alpha = NA, linetype = "solid"),
          required_aes = c("x", "y")
)
```

# Draw figure

```{r figure, echo = FALSE}
violin <- ggplot(res, aes(x = species, y = time.ratio.ln)) +
  labs(y = "preference strength", x = "species") +
  # Preference = 0
  geom_hline(yintercept = 0, linetype = "dotted") +
  # Violin plot on right side
  geom_flat_violin(trim=FALSE, scale="count", fill = "grey80", colour = "white") +
  # Bar plot
  stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), 
               size = 0.5, geom = "pointrange", position = position_nudge(0.05)) +
  # Dot plot on left side
  geom_dotplot(binaxis = "y", dotsize = 0.8, stackdir = "down", binwidth = 0.1, 
               position = position_nudge(-0.025)) +
  # theme
  theme(axis.text.x = element_text(size=12), axis.text.y = element_text(size=12),
        axis.title.x = element_text(size=13), axis.title.y = element_text(size=13),
        panel.background=element_rect(fill='white', colour='black', size=0.3),
        panel.grid=element_blank(),legend.position="none")
violin
ggsave(file = 'plot_rat.ln.png', plot = violin, width = 3, height = 3.5)
ggsave(file = 'plot_rat.ln.eps', plot = violin, width = 3, height = 3.5)
```


## Appendix: Model choice on effect of male body size on its preference for females
```{r FL, echo=FALSE}
prob_dens.FL <- . %>% {
  ggplot(., aes(FL)) + geom_density(colour = "#9BD3EE", fill = "#D0F3FF70")
}
prob_dens.FL(TH) + ggtitle("Body size | UGUI") -> p1
prob_dens.FL(TS) + ggtitle("Body size | EZO") -> p2
grid.arrange(p1, p2, ncol = 2)

mod.TH <- glm(time.dif ~ FL, family = "gaussian", data = TH)
dredge(mod.TH, rank = "BIC", options(na.action = "na.fail"))
mod.TS <- glm(time.dif ~ FL, family = "gaussian", data = TS)
dredge(mod.TS, rank = "BIC", options(na.action = "na.fail"))

mod.TH <- glm(time.ratio.ln ~ FL, family = "gaussian", data = TH)
dredge(mod.TH, rank = "BIC", options(na.action = "na.fail"))
mod.TS <- glm(time.ratio.ln ~ FL, family = "gaussian", data = TS)
dredge(mod.TS, rank = "BIC", options(na.action = "na.fail"))
```
